server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  config: classpath:log4j2.xml


spring:
  application:
    name: ferrari-flux
  zipkin:
    base-url: http://192.168.85.131:9411
  sleuth:
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1.0

